# Generated by Django 2.2.7 on 2019-12-14 06:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.FileField(upload_to='categories/media/images/')),
            ],
        ),
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spname', models.CharField(default=' ', max_length=150)),
                ('spownm', models.CharField(default=' ', max_length=100)),
                ('mob', models.BigIntegerField(unique=True)),
                ('city', models.CharField(max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cn', models.CharField(default=' ', max_length=100)),
                ('image', models.FileField(upload_to='categories/media/images/')),
                ('tname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Catg')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pn', models.CharField(default=' ', max_length=100)),
                ('img', models.FileField(upload_to='categories/media/images/')),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Type')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chn', models.CharField(default=' ', max_length=1000)),
                ('chname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Product')),
            ],
        ),
    ]
